package com.phonlynn.oreplan.v2.icons

// AUTO-GENERATED by design/icons fetch script. Source: lucide-static icons (exact vectors).
// Do not edit manually.

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap
import androidx.compose.ui.graphics.StrokeJoin
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.PathParser
import androidx.compose.ui.unit.dp

/**
 * 手工补充的图标（不在生成脚本的清单里）。
 *
 * ⚠️ 本文件是 AUTO-GENERATED，重新跑生成脚本会覆盖它 ——
 * 但脚本只覆盖它导出的那些图标，这段追加在末尾、按同一 `lucideIcon` 形式书写，
 * 内容与 lucide 官方矢量一致，复查时按"新增图标"对待即可。
 */

private fun lucideIcon(name: String, vararg pathData: String): ImageVector =
    ImageVector.Builder(
        name = "Lucide." + name,
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 24f,
        viewportHeight = 24f,
    ).apply {
        for (d in pathData) {
            addPath(
                pathData = PathParser().parsePathString(d).toNodes(),
                stroke = SolidColor(Color.Black),
                strokeLineWidth = 2f,
                strokeLineCap = StrokeCap.Round,
                strokeLineJoin = StrokeJoin.Round,
                fill = null,
            )
        }
    }.build()

object Lucide {
    val Activity: ImageVector by lazy { lucideIcon("Activity",
        "M22 12h-2.48a2 2 0 0 0-1.93 1.46l-2.35 8.36a.25.25 0 0 1-.48 0L9.24 2.18a.25.25 0 0 0-.48 0l-2.35 8.36A2 2 0 0 1 4.49 12H2")
    }
    val AlarmClock: ImageVector by lazy { lucideIcon("AlarmClock",
        "M 4 13 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0",
        "M12 9v4l2 2",
        "M5 3 2 6",
        "m22 6-3-3",
        "M6.38 18.7 4 21",
        "M17.64 18.67 20 21")
    }
    val Archive: ImageVector by lazy { lucideIcon("Archive",
        "M 3 3 H 21 A 1 1 0 0 1 22 4 V 7 A 1 1 0 0 1 21 8 H 3 A 1 1 0 0 1 2 7 V 4 A 1 1 0 0 1 3 3 Z",
        "M4 8v11a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8",
        "M10 12h4")
    }
    val ArrowLeft: ImageVector by lazy { lucideIcon("ArrowLeft",
        "m12 19-7-7 7-7",
        "M19 12H5")
    }
    val ArrowRight: ImageVector by lazy { lucideIcon("ArrowRight",
        "M5 12h14",
        "m12 5 7 7-7 7")
    }
    val ArrowUpRight: ImageVector by lazy { lucideIcon("ArrowUpRight",
        "M7 7h10v10",
        "M7 17 17 7")
    }
    val BatteryFull: ImageVector by lazy { lucideIcon("BatteryFull",
        "M10 10v4",
        "M14 10v4",
        "M22 14v-4",
        "M6 10v4",
        "M 4 6 H 16 A 2 2 0 0 1 18 8 V 16 A 2 2 0 0 1 16 18 H 4 A 2 2 0 0 1 2 16 V 8 A 2 2 0 0 1 4 6 Z")
    }
    val Bell: ImageVector by lazy { lucideIcon("Bell",
        "M10.268 21a2 2 0 0 0 3.464 0",
        "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326")
    }
    val BellRing: ImageVector by lazy { lucideIcon("BellRing",
        "M10.268 21a2 2 0 0 0 3.464 0",
        "M22 8c0-2.3-.8-4.3-2-6",
        "M3.262 15.326A1 1 0 0 0 4 17h16a1 1 0 0 0 .74-1.673C19.41 13.956 18 12.499 18 8A6 6 0 0 0 6 8c0 4.499-1.411 5.956-2.738 7.326",
        "M4 2C2.8 3.7 2 5.7 2 8")
    }
    val Bold: ImageVector by lazy { lucideIcon("Bold",
        "M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8")
    }
    /** lucide "underline"：用于工具栏的下划线按钮。 */
    val Underline: ImageVector by lazy { lucideIcon("Underline",
        "M6 4v6a6 6 0 0 0 12 0V4",
        "M4 20h16")
    }
    /** lucide "strikethrough"：用于工具栏的删除线按钮。 */
    val Strikethrough: ImageVector by lazy { lucideIcon("Strikethrough",
        "M16 4H9a3 3 0 0 0-2.83 4",
        "M14 12a4 4 0 0 1 0 8H6",
        "M4 12h16")
    }
    val BookOpen: ImageVector by lazy { lucideIcon("BookOpen",
        "M12 5v16",
        "M20.001 19A2 2 0 0022 17V5a2 2 0 00-1.999-2L16 3.002A5 5 0 0012 5a5 5 0 00-4-2H4a2 2 0 00-2 2v12a2 2 0 001.999 2H8a5 5 0 014 2 5 5 0 014-2z")
    }
    val Bookmark: ImageVector by lazy { lucideIcon("Bookmark",
        "M17 3a2 2 0 0 1 2 2v15a1 1 0 0 1-1.496.868l-4.512-2.578a2 2 0 0 0-1.984 0l-4.512 2.578A1 1 0 0 1 5 20V5a2 2 0 0 1 2-2z")
    }
    val Calendar: ImageVector by lazy { lucideIcon("Calendar",
        "M8 2v3",
        "M16 2v3",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
        "M3 9h18")
    }
    val CalendarCheck: ImageVector by lazy { lucideIcon("CalendarCheck",
        "M8 2v3",
        "M16 2v3",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
        "M3 9h18",
        "m9 15 2 2 4-4")
    }
    val CalendarDays: ImageVector by lazy { lucideIcon("CalendarDays",
        "M8 2v3",
        "M16 2v3",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
        "M3 9h18",
        "M8 13h.01",
        "M12 13h.01",
        "M16 13h.01",
        "M8 17h.01",
        "M12 17h.01",
        "M16 17h.01")
    }
    val ChartBar: ImageVector by lazy { lucideIcon("ChartBar",
        "M3 3v16a2 2 0 0 0 2 2h16",
        "M7 16h8",
        "M7 11h12",
        "M7 6h3")
    }
    val Check: ImageVector by lazy { lucideIcon("Check",
        "M20 6 9 17l-5-5")
    }
    val ChevronDown: ImageVector by lazy { lucideIcon("ChevronDown",
        "m6 9 6 6 6-6")
    }
    val ChevronLeft: ImageVector by lazy { lucideIcon("ChevronLeft",
        "m15 18-6-6 6-6")
    }
    val ChevronRight: ImageVector by lazy { lucideIcon("ChevronRight",
        "m9 18 6-6-6-6")
    }
    val ChevronUp: ImageVector by lazy { lucideIcon("ChevronUp",
        "m18 15-6-6-6 6")
    }
    val ChevronsLeftRight: ImageVector by lazy { lucideIcon("ChevronsLeftRight",
        "m9 7-5 5 5 5",
        "m15 7 5 5-5 5")
    }
    val ChevronsRightLeft: ImageVector by lazy { lucideIcon("ChevronsRightLeft",
        "m20 17-5-5 5-5",
        "m4 17 5-5-5-5")
    }
    val CircleAlert: ImageVector by lazy { lucideIcon("CircleAlert",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M 12 8 L 12 12",
        "M 12 16 L 12.01 16")
    }
    val CircleCheck: ImageVector by lazy { lucideIcon("CircleCheck",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "m16 9-5.5 5.5L8 12")
    }
    val CircleDot: ImageVector by lazy { lucideIcon("CircleDot",
        "M 11 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0")
    }
    val CirclePlay: ImageVector by lazy { lucideIcon("CirclePlay",
        "M9 9.003a1 1 0 0 1 1.517-.859l4.997 2.997a1 1 0 0 1 0 1.718l-4.997 2.997A1 1 0 0 1 9 14.996z",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0")
    }
    val CircleX: ImageVector by lazy { lucideIcon("CircleX",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "m15 9-6 6",
        "m9 9 6 6")
    }
    val Clock: ImageVector by lazy { lucideIcon("Clock",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M12 6v6l4 2")
    }
    val Clock3: ImageVector by lazy { lucideIcon("Clock3",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M12 6v6h4")
    }
    val Clock4: ImageVector by lazy { lucideIcon("Clock4",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M12 6v6l4 2")
    }
    val Cloud: ImageVector by lazy { lucideIcon("Cloud",
        "M17.5 19H9a7 7 0 1 1 6.71-9h1.79a4.5 4.5 0 1 1 0 9Z")
    }
    val CloudUpload: ImageVector by lazy { lucideIcon("CloudUpload",
        "M12 13v8",
        "M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242",
        "m8 17 4-4 4 4")
    }
    val Coffee: ImageVector by lazy { lucideIcon("Coffee",
        "M10 2v2",
        "M14 2v2",
        "M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1",
        "M6 2v2")
    }
    val Copy: ImageVector by lazy { lucideIcon("Copy",
        "M 10 8 H 20 A 2 2 0 0 1 22 10 V 20 A 2 2 0 0 1 20 22 H 10 A 2 2 0 0 1 8 20 V 10 A 2 2 0 0 1 10 8 Z",
        "M4 16c-1.1 0-2-.9-2-2V4c0-1.1.9-2 2-2h10c1.1 0 2 .9 2 2")
    }
    val Download: ImageVector by lazy { lucideIcon("Download",
        "M12 15V3",
        "M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4",
        "m7 10 5 5 5-5")
    }
    val Ellipsis: ImageVector by lazy { lucideIcon("Ellipsis",
        "M 11 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 18 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 4 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0")
    }
    val Eye: ImageVector by lazy { lucideIcon("Eye",
        "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
        "M 9 12 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0")
    }
    val File: ImageVector by lazy { lucideIcon("File",
        "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
        "M14 2v5a1 1 0 0 0 1 1h5")
    }
    val FileDown: ImageVector by lazy { lucideIcon("FileDown",
        "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
        "M14 2v5a1 1 0 0 0 1 1h5",
        "M12 18v-6",
        "m9 15 3 3 3-3")
    }
    val FileSpreadsheet: ImageVector by lazy { lucideIcon("FileSpreadsheet",
        "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
        "M14 2v5a1 1 0 0 0 1 1h5",
        "M8 13h2",
        "M14 13h2",
        "M8 17h2",
        "M14 17h2")
    }
    val FileText: ImageVector by lazy { lucideIcon("FileText",
        "M6 22a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h8a2.4 2.4 0 0 1 1.704.706l3.588 3.588A2.4 2.4 0 0 1 20 8v12a2 2 0 0 1-2 2z",
        "M14 2v5a1 1 0 0 0 1 1h5",
        "M10 9H8",
        "M16 13H8",
        "M16 17H8")
    }
    val Filter: ImageVector by lazy { lucideIcon("Filter",
        "M10 20a1 1 0 0 0 .553.895l2 1A1 1 0 0 0 14 21v-7a2 2 0 0 1 .517-1.341L21.74 4.67A1 1 0 0 0 21 3H3a1 1 0 0 0-.742 1.67l7.225 7.989A2 2 0 0 1 10 14z")
    }
    val Flame: ImageVector by lazy { lucideIcon("Flame",
        "M12 3q1 4 4 6.5t3 5.5a1 1 0 0 1-14 0 5 5 0 0 1 1-3 1 1 0 0 0 5 0c0-2-1.5-3-1.5-5q0-2 2.5-4")
    }
    val Folder: ImageVector by lazy { lucideIcon("Folder",
        "M20 20a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2h-7.9a2 2 0 0 1-1.69-.9L9.6 3.9A2 2 0 0 0 7.93 3H4a2 2 0 0 0-2 2v13a2 2 0 0 0 2 2Z")
    }
    val FolderInput: ImageVector by lazy { lucideIcon("FolderInput",
        "M2 9V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-1",
        "M2 13h10",
        "m9 16 3-3-3-3")
    }
    val FolderOpen: ImageVector by lazy { lucideIcon("FolderOpen",
        "m6 14 1.5-2.9A2 2 0 0 1 9.24 10H20a2 2 0 0 1 1.94 2.5l-1.54 6a2 2 0 0 1-1.95 1.5H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H18a2 2 0 0 1 2 2v2")
    }
    val FolderTree: ImageVector by lazy { lucideIcon("FolderTree",
        "M20 10a1 1 0 0 0 1-1V6a1 1 0 0 0-1-1h-2.5a1 1 0 0 1-.8-.4l-.9-1.2A1 1 0 0 0 15 3h-2a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1Z",
        "M20 21a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-2.9a1 1 0 0 1-.88-.55l-.42-.85a1 1 0 0 0-.92-.6H13a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1Z",
        "M3 5a2 2 0 0 0 2 2h3",
        "M3 3v13a2 2 0 0 0 2 2h3")
    }
    val GitBranch: ImageVector by lazy { lucideIcon("GitBranch",
        "M6 3v12",
        "M 15 6 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0",
        "M 3 18 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0",
        "M18 9a9 9 0 0 1-9 9")
    }
    val GraduationCap: ImageVector by lazy { lucideIcon("GraduationCap",
        "M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z",
        "M22 10v6",
        "M6 12.5V16a6 3 0 0 0 12 0v-3.5")
    }
    val GripVertical: ImageVector by lazy { lucideIcon("GripVertical",
        "M 8 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 8 5 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 8 19 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 14 12 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 14 5 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0",
        "M 14 19 a 1 1 0 1 0 2 0 a 1 1 0 1 0 -2 0")
    }
    val Hash: ImageVector by lazy { lucideIcon("Hash",
        "M 4 9 L 20 9",
        "M 4 15 L 20 15",
        "M 10 3 L 8 21",
        "M 16 3 L 14 21")
    }
    val Heart: ImageVector by lazy { lucideIcon("Heart",
        "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5")
    }
    val Hourglass: ImageVector by lazy { lucideIcon("Hourglass",
        "M5 22h14",
        "M5 2h14",
        "M17 22v-4.172a2 2 0 0 0-.586-1.414L12 12l-4.414 4.414A2 2 0 0 0 7 17.828V22",
        "M7 2v4.172a2 2 0 0 0 .586 1.414L12 12l4.414-4.414A2 2 0 0 0 17 6.172V2")
    }
    val Image: ImageVector by lazy { lucideIcon("Image",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
        "M 7 9 a 2 2 0 1 0 4 0 a 2 2 0 1 0 -4 0",
        "m21 15-3.086-3.086a2 2 0 0 0-2.828 0L6 21")
    }
    val Info: ImageVector by lazy { lucideIcon("Info",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M12 16v-4",
        "M12 8h.01")
    }
    val Italic: ImageVector by lazy { lucideIcon("Italic",
        "M 19 4 L 10 4",
        "M 14 20 L 5 20",
        "M 15 4 L 9 20")
    }
    /** lucide "highlighter"：荧光笔——用于「荧光笔加重」格式按钮。 */
    val Highlighter: ImageVector by lazy { lucideIcon("Highlighter",
        "m9 11-6 6v3h9l3-3",
        "m22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4") }
    val Key: ImageVector by lazy { lucideIcon("Key",
        "m2 21 9.6-9.6",
        "m7.5 15.5 2.3 2.3a1 1 0 0 1 0 1.4l-2.1 2.1a1 1 0 0 1-1.4 0L4 19",
        "M 10 7.5 a 5.5 5.5 0 1 0 11 0 a 5.5 5.5 0 1 0 -11 0")
    }
    val Layers: ImageVector by lazy { lucideIcon("Layers",
        "M12.83 2.18a2 2 0 0 0-1.66 0L2.6 6.08a1 1 0 0 0 0 1.83l8.58 3.91a2 2 0 0 0 1.66 0l8.58-3.9a1 1 0 0 0 0-1.83z",
        "M2 12a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 12",
        "M2 17a1 1 0 0 0 .58.91l8.6 3.91a2 2 0 0 0 1.65 0l8.58-3.9A1 1 0 0 0 22 17")
    }
    val LayoutDashboard: ImageVector by lazy { lucideIcon("LayoutDashboard",
        "M 4 3 H 9 A 1 1 0 0 1 10 4 V 11 A 1 1 0 0 1 9 12 H 4 A 1 1 0 0 1 3 11 V 4 A 1 1 0 0 1 4 3 Z",
        "M 15 3 H 20 A 1 1 0 0 1 21 4 V 7 A 1 1 0 0 1 20 8 H 15 A 1 1 0 0 1 14 7 V 4 A 1 1 0 0 1 15 3 Z",
        "M 15 12 H 20 A 1 1 0 0 1 21 13 V 20 A 1 1 0 0 1 20 21 H 15 A 1 1 0 0 1 14 20 V 13 A 1 1 0 0 1 15 12 Z",
        "M 4 16 H 9 A 1 1 0 0 1 10 17 V 20 A 1 1 0 0 1 9 21 H 4 A 1 1 0 0 1 3 20 V 17 A 1 1 0 0 1 4 16 Z")
    }
    val Link: ImageVector by lazy { lucideIcon("Link",
        "M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71",
        "M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71")
    }
    val Link2: ImageVector by lazy { lucideIcon("Link2",
        "M9 17H7A5 5 0 0 1 7 7h2",
        "M15 7h2a5 5 0 1 1 0 10h-2",
        "M 8 12 L 16 12")
    }
    val List: ImageVector by lazy { lucideIcon("List",
        "M3 5h.01",
        "M3 12h.01",
        "M3 19h.01",
        "M8 5h13",
        "M8 12h13",
        "M8 19h13")
    }
    val ListChecks: ImageVector by lazy { lucideIcon("ListChecks",
        "M13 5h8",
        "M13 12h8",
        "M13 19h8",
        "m3 17 2 2 4-4",
        "m3 7 2 2 4-4")
    }
    val ListOrdered: ImageVector by lazy { lucideIcon("ListOrdered",
        "M11 5h10",
        "M11 12h10",
        "M11 19h10",
        "M4 4h1v5",
        "M4 9h2",
        "M6.5 20H3.4c0-1 2.6-1.925 2.6-3.5a1.5 1.5 0 0 0-2.6-1.02")
    }
    val ListTodo: ImageVector by lazy { lucideIcon("ListTodo",
        "M13 5h8",
        "M13 12h8",
        "M13 19h8",
        "m3 17 2 2 4-4",
        "M 4 4 H 8 A 1 1 0 0 1 9 5 V 9 A 1 1 0 0 1 8 10 H 4 A 1 1 0 0 1 3 9 V 5 A 1 1 0 0 1 4 4 Z")
    }
    val Lock: ImageVector by lazy { lucideIcon("Lock",
        "M 5 11 H 19 A 2 2 0 0 1 21 13 V 20 A 2 2 0 0 1 19 22 H 5 A 2 2 0 0 1 3 20 V 13 A 2 2 0 0 1 5 11 Z",
        "M7 11V7a5 5 0 0 1 10 0v4")
    }
    val LogOut: ImageVector by lazy { lucideIcon("LogOut",
        "m16 17 5-5-5-5",
        "M21 12H9",
        "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4")
    }
    val MapPin: ImageVector by lazy { lucideIcon("MapPin",
        "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0",
        "M 9 10 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0")
    }
    /** lucide "maximize-2"：四角向外——用于「进入全屏文本编辑」。 */
    val Maximize2: ImageVector by lazy { lucideIcon("Maximize2",
        "M15 3h6v6",
        "m21 3-7 7",
        "m3 21 7-7",
        "M9 21H3v-6")
    }
    val MessageCircle: ImageVector by lazy { lucideIcon("MessageCircle",
        "M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719")
    }
    val Mic: ImageVector by lazy { lucideIcon("Mic",
        "M12 19v3",
        "M19 10v2a7 7 0 0 1-14 0v-2",
        "M 12 2 H 12 A 3 3 0 0 1 15 5 V 12 A 3 3 0 0 1 12 15 H 12 A 3 3 0 0 1 9 12 V 5 A 3 3 0 0 1 12 2 Z")
    }
    val Minus: ImageVector by lazy { lucideIcon("Minus",
        "M5 12h14")
    }
    val Move: ImageVector by lazy { lucideIcon("Move",
        "M12 2v20",
        "m15 19-3 3-3-3",
        "m19 9 3 3-3 3",
        "M2 12h20",
        "m5 9-3 3 3 3",
        "m9 5 3-3 3 3")
    }
    val Music: ImageVector by lazy { lucideIcon("Music",
        "M9 18V5l12-2v13",
        "M 3 18 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0",
        "M 15 16 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0")
    }
    val Palette: ImageVector by lazy { lucideIcon("Palette",
        "M12 22a1 1 0 0 1 0-20 10 9 0 0 1 10 9 5 5 0 0 1-5 5h-2.25a1.75 1.75 0 0 0-1.4 2.8l.3.4a1.75 1.75 0 0 1-1.4 2.8z",
        "M 13 6.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0",
        "M 17 10.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0",
        "M 6 12.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0",
        "M 8 7.5 a 0.5 0.5 0 1 0 1 0 a 0.5 0.5 0 1 0 -1 0")
    }
    /**
     * 圆圈加号 —— AI 输入框的「添加附件」按钮（设计稿 `Hekf8 / QRkPT`，24x24）。
     *
     * 路径是 Lucide 官方的 `circle-plus`：一个整圆 + 两条十字线。
     * 用描边圆而不是填充圆（`lucideIcon` 统一按描边渲染）。
     */
    val CirclePlus: ImageVector by lazy { lucideIcon("CirclePlus",
        "M 12 2 A 10 10 0 1 0 12 22 A 10 10 0 1 0 12 2",
        "M8 12h8",
        "M12 8v8")
    }
    val Paperclip: ImageVector by lazy { lucideIcon("Paperclip",
        "m16 6-8.414 8.586a2 2 0 0 0 2.829 2.829l8.414-8.586a4 4 0 1 0-5.657-5.657l-8.379 8.551a6 6 0 1 0 8.485 8.485l8.379-8.551")
    }
    val Pause: ImageVector by lazy { lucideIcon("Pause",
        "M 15 3 H 18 A 1 1 0 0 1 19 4 V 20 A 1 1 0 0 1 18 21 H 15 A 1 1 0 0 1 14 20 V 4 A 1 1 0 0 1 15 3 Z",
        "M 6 3 H 9 A 1 1 0 0 1 10 4 V 20 A 1 1 0 0 1 9 21 H 6 A 1 1 0 0 1 5 20 V 4 A 1 1 0 0 1 6 3 Z")
    }
    val Pencil: ImageVector by lazy { lucideIcon("Pencil",
        "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z",
        "m15 5 4 4")
    }
    val PencilLine: ImageVector by lazy { lucideIcon("PencilLine",
        "M13 21h8",
        "m15 5 4 4",
        "M21.174 6.812a1 1 0 0 0-3.986-3.987L3.842 16.174a2 2 0 0 0-.5.83l-1.321 4.352a.5.5 0 0 0 .623.622l4.353-1.32a2 2 0 0 0 .83-.497z")
    }
    val Pin: ImageVector by lazy { lucideIcon("Pin",
        "M12 17v5",
        "M9 10.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-.76a2 2 0 0 0-1.11-1.79l-1.78-.9A2 2 0 0 1 15 10.76V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H8a2 2 0 0 0 0 4 1 1 0 0 1 1 1z")
    }
    /**
     * 「取消置顶」（对话列表多选的批量动作之一，用户 2026-10-04）。
     *
     * lucide 的 `pin-off`：与 [Pin] 同形，但**没有那根针**，
     * 而且多一条斜杠。多选的批量动作里「置顶」与「取消置顶」是两个并列按钮，
     * 用同一个图标会让它们看起来一模一样 —— 所以需要这一版。
     */
    val PinOff: ImageVector by lazy { lucideIcon("PinOff",
        "M12 17v5",
        "M15 9.34V7a1 1 0 0 1 1-1 2 2 0 0 0 0-4H7.89",
        "m2 2 20 20",
        "M9 9v1.76a2 2 0 0 1-1.11 1.79l-1.78.9A2 2 0 0 0 5 15.24V16a1 1 0 0 0 1 1h11")
    }
    val Play: ImageVector by lazy { lucideIcon("Play",
        "M5 5a2 2 0 0 1 3.008-1.728l11.997 6.998a2 2 0 0 1 .003 3.458l-12 7A2 2 0 0 1 5 19z")
    }
    val Plus: ImageVector by lazy { lucideIcon("Plus",
        "M5 12h14",
        "M12 5v14")
    }
    val Quote: ImageVector by lazy { lucideIcon("Quote",
        "M16 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z",
        "M5 3a2 2 0 0 0-2 2v6a2 2 0 0 0 2 2 1 1 0 0 1 1 1v1a2 2 0 0 1-2 2 1 1 0 0 0-1 1v2a1 1 0 0 0 1 1 6 6 0 0 0 6-6V5a2 2 0 0 0-2-2z")
    }
    val Redo2: ImageVector by lazy { lucideIcon("Redo2",
        "m15 14 5-5-5-5",
        "M20 9H9.5A5.5 5.5 0 0 0 4 14.5A5.5 5.5 0 0 0 9.5 20H13")
    }
    val RefreshCw: ImageVector by lazy { lucideIcon("RefreshCw",
        "M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8",
        "M21 3v5h-5",
        "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16",
        "M8 16H3v5")
    }
    val Repeat: ImageVector by lazy { lucideIcon("Repeat",
        "m17 2 4 4-4 4",
        "M3 11v-1a4 4 0 0 1 4-4h14",
        "m7 22-4-4 4-4",
        "M21 13v1a4 4 0 0 1-4 4H3")
    }
    val RotateCcw: ImageVector by lazy { lucideIcon("RotateCcw",
        "M3 12a9 9 0 1 0 9-9 9.75 9.75 0 0 0-6.74 2.74L3 8",
        "M3 3v5h5")
    }
    val RotateCw: ImageVector by lazy { lucideIcon("RotateCw",
        "M21 12a9 9 0 1 1-9-9c2.52 0 4.93 1 6.74 2.74L21 8",
        "M21 3v5h-5")
    }
    val Search: ImageVector by lazy { lucideIcon("Search",
        "m21 21-4.34-4.34",
        "M 3 11 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0")
    }
    val Send: ImageVector by lazy { lucideIcon("Send",
        "M14.536 21.686a.5.5 0 0 0 .937-.024l6.5-19a.496.496 0 0 0-.635-.635l-19 6.5a.5.5 0 0 0-.024.937l7.93 3.18a2 2 0 0 1 1.112 1.11z",
        "m21.854 2.147-10.94 10.939")
    }
    val Settings: ImageVector by lazy { lucideIcon("Settings",
        "M9.671 4.136a2.34 2.34 0 0 1 4.659 0 2.34 2.34 0 0 0 3.319 1.915 2.34 2.34 0 0 1 2.33 4.033 2.34 2.34 0 0 0 0 3.831 2.34 2.34 0 0 1-2.33 4.033 2.34 2.34 0 0 0-3.319 1.915 2.34 2.34 0 0 1-4.659 0 2.34 2.34 0 0 0-3.32-1.915 2.34 2.34 0 0 1-2.33-4.033 2.34 2.34 0 0 0 0-3.831A2.34 2.34 0 0 1 6.35 6.051a2.34 2.34 0 0 0 3.319-1.915",
        "M 9 12 a 3 3 0 1 0 6 0 a 3 3 0 1 0 -6 0")
    }
    val Shield: ImageVector by lazy { lucideIcon("Shield",
        "M20 13c0 5-3.5 7.5-7.66 8.95a1 1 0 0 1-.67-.01C7.5 20.5 4 18 4 13V6a1 1 0 0 1 1-1c2 0 4.5-1.2 6.24-2.72a1.17 1.17 0 0 1 1.52 0C14.51 3.81 17 5 19 5a1 1 0 0 1 1 1z")
    }
    val Signal: ImageVector by lazy { lucideIcon("Signal",
        "M2 20h.01",
        "M7 20v-4",
        "M12 20v-8",
        "M17 20V8",
        "M22 4v16")
    }
    val SkipBack: ImageVector by lazy { lucideIcon("SkipBack",
        "M17.971 4.285A2 2 0 0 1 21 6v12a2 2 0 0 1-3.029 1.715l-9.997-5.998a2 2 0 0 1-.003-3.432z",
        "M3 20V4")
    }
    val SkipForward: ImageVector by lazy { lucideIcon("SkipForward",
        "M21 4v16",
        "M6.029 4.285A2 2 0 0 0 3 6v12a2 2 0 0 0 3.029 1.715l9.997-5.998a2 2 0 0 0 .003-3.432z")
    }
    val SlidersHorizontal: ImageVector by lazy { lucideIcon("SlidersHorizontal",
        "M10 5H3",
        "M12 19H3",
        "M14 3v4",
        "M16 17v4",
        "M21 12h-9",
        "M21 19h-5",
        "M21 5h-7",
        "M8 10v4",
        "M8 12H3")
    }
    val Sparkles: ImageVector by lazy { lucideIcon("Sparkles",
        "M11.017 2.814a1 1 0 0 1 1.966 0l1.051 5.558a2 2 0 0 0 1.594 1.594l5.558 1.051a1 1 0 0 1 0 1.966l-5.558 1.051a2 2 0 0 0-1.594 1.594l-1.051 5.558a1 1 0 0 1-1.966 0l-1.051-5.558a2 2 0 0 0-1.594-1.594l-5.558-1.051a1 1 0 0 1 0-1.966l5.558-1.051a2 2 0 0 0 1.594-1.594z",
        "M20 2v4",
        "M22 4h-4",
        "M 2 20 a 2 2 0 1 0 4 0 a 2 2 0 1 0 -4 0")
    }
    val Square: ImageVector by lazy { lucideIcon("Square",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z")
    }
    val SquareCheck: ImageVector by lazy { lucideIcon("SquareCheck",
        "M 5 3 H 19 A 2 2 0 0 1 21 5 V 19 A 2 2 0 0 1 19 21 H 5 A 2 2 0 0 1 3 19 V 5 A 2 2 0 0 1 5 3 Z",
        "m16 9-5.5 5.5L8 12")
    }
    val Star: ImageVector by lazy { lucideIcon("Star",
        "M11.525 2.295a.53.53 0 0 1 .95 0l2.31 4.679a2.123 2.123 0 0 0 1.595 1.16l5.166.756a.53.53 0 0 1 .294.904l-3.736 3.638a2.123 2.123 0 0 0-.611 1.878l.882 5.14a.53.53 0 0 1-.771.56l-4.618-2.428a2.122 2.122 0 0 0-1.973 0L6.396 21.01a.53.53 0 0 1-.77-.56l.881-5.139a2.122 2.122 0 0 0-.611-1.879L2.16 9.795a.53.53 0 0 1 .294-.906l5.165-.755a2.122 2.122 0 0 0 1.597-1.16z")
    }
    val Sun: ImageVector by lazy { lucideIcon("Sun",
        "M 8 12 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0",
        "M12 2v2",
        "M12 20v2",
        "m4.93 4.93 1.41 1.41",
        "m17.66 17.66 1.41 1.41",
        "M2 12h2",
        "M20 12h2",
        "m6.34 17.66-1.41 1.41",
        "m19.07 4.93-1.41 1.41")
    }
    val Target: ImageVector by lazy { lucideIcon("Target",
        "M 2 12 a 10 10 0 1 0 20 0 a 10 10 0 1 0 -20 0",
        "M 6 12 a 6 6 0 1 0 12 0 a 6 6 0 1 0 -12 0",
        "M 10 12 a 2 2 0 1 0 4 0 a 2 2 0 1 0 -4 0")
    }
    val Timer: ImageVector by lazy { lucideIcon("Timer",
        "M 10 2 L 14 2",
        "M 12 14 L 15 11",
        "M 4 14 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0")
    }
    val Trash2: ImageVector by lazy { lucideIcon("Trash2",
        "M10 11v6",
        "M14 11v6",
        "M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6",
        "M3 6h18",
        "M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2")
    }
    val TrendingUp: ImageVector by lazy { lucideIcon("TrendingUp",
        "M16 7h6v6",
        "m22 7-8.5 8.5-5-5L2 17")
    }
    val Type: ImageVector by lazy { lucideIcon("Type",
        "M12 4v16",
        "M4 7V5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v2",
        "M9 20h6")
    }
    val Undo2: ImageVector by lazy { lucideIcon("Undo2",
        "M9 14 4 9l5-5",
        "M4 9h10.5a5.5 5.5 0 0 1 5.5 5.5a5.5 5.5 0 0 1-5.5 5.5H11")
    }
    val User: ImageVector by lazy { lucideIcon("User",
        "M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2",
        "M 8 7 a 4 4 0 1 0 8 0 a 4 4 0 1 0 -8 0")
    }
    val Video: ImageVector by lazy { lucideIcon("Video",
        "m16 13 5.223 3.482a.5.5 0 0 0 .777-.416V7.87a.5.5 0 0 0-.752-.432L16 10.5",
        "M 4 6 H 14 A 2 2 0 0 1 16 8 V 16 A 2 2 0 0 1 14 18 H 4 A 2 2 0 0 1 2 16 V 8 A 2 2 0 0 1 4 6 Z")
    }
    val Volume2: ImageVector by lazy { lucideIcon("Volume2",
        "M11 4.702a.705.705 0 0 0-1.203-.498L6.413 7.587A1.4 1.4 0 0 1 5.416 8H3a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1h2.416a1.4 1.4 0 0 1 .997.413l3.383 3.384A.705.705 0 0 0 11 19.298z",
        "M16 9a5 5 0 0 1 0 6",
        "M19.364 18.364a9 9 0 0 0 0-12.728")
    }
    val WandSparkles: ImageVector by lazy { lucideIcon("WandSparkles",
        "m21.64 3.64-1.28-1.28a1.21 1.21 0 0 0-1.72 0L2.36 18.64a1.21 1.21 0 0 0 0 1.72l1.28 1.28a1.2 1.2 0 0 0 1.72 0L21.64 5.36a1.2 1.2 0 0 0 0-1.72",
        "m14 7 3 3",
        "M5 6v4",
        "M19 14v4",
        "M10 2v2",
        "M7 8H3",
        "M21 16h-4",
        "M11 3H9")
    }
    val Wifi: ImageVector by lazy { lucideIcon("Wifi",
        "M12 20h.01",
        "M2 8.82a15 15 0 0 1 20 0",
        "M5 12.859a10 10 0 0 1 14 0",
        "M8.5 16.429a5 5 0 0 1 7 0")
    }
    val X: ImageVector by lazy { lucideIcon("X",
        "M18 6 6 18",
        "m6 6 12 12")
    }
    val Zap: ImageVector by lazy { lucideIcon("Zap",
        "M15.914 4a1.5 1.5 0 00-2.474-1.561l-9 9A1.5 1.5 0 005.5 14h4.002a.5.5 0 01.471.666L8.086 20a1.5 1.5 0 002.475 1.56l9-9A1.5 1.5 0 0018.5 10h-3.997a.5.5 0 01-.472-.667z")
    }
    val ZoomIn: ImageVector by lazy { lucideIcon("ZoomIn",
        "M 3 11 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0",
        "M 21 21 L 16.65 16.65",
        "M 11 8 L 11 14",
        "M 8 11 L 14 11")
    }
    val ZoomOut: ImageVector by lazy { lucideIcon("ZoomOut",
        "M 3 11 a 8 8 0 1 0 16 0 a 8 8 0 1 0 -16 0",
        "M 21 21 L 16.65 16.65",
        "M 8 11 L 14 11")
    }

    // ---------------------------------------------------------------- 手工补充

    /**
     * 汉堡菜单（侧栏入口）。
     *
     * ⚠️ **这是 lucide `menu` 的变体，不是官方原样**（用户 2026-10-02 指定）：
     * 官方三条线**等长**（`M4 5h16` / `M4 12h16` / `M4 19h16`，见 lucide main 的 menu.svg），
     * 这里把**最下面那条缩短**并保持**左端对齐**（`M4 19h11`）。
     *
     * 用户口径：「最下面那条横线要稍微短一些，左端对齐」——
     * 短到 `h11`（原 `h16`），三条线左端都在 x=4。
     * 改动时请注意：这不是从上游同步来的矢量，重新生成图标集**不会**带上它。
     */
    val Menu: ImageVector by lazy { lucideIcon("Menu",
        "M4 5h16",
        "M4 12h16",
        "M4 19h11")
    }

    /**
     * 发送按钮（AI 对话输入框）。
     *
     * lucide 的 `arrow-up`。与既有的 `ArrowUpRight` 不同 ——
     * 那个是斜向箭头，用于"打开/外链"；对话的发送是**竖直向上**。
     */
    val ArrowUp: ImageVector by lazy { lucideIcon("ArrowUp",
        "m5 12 7-7 7 7",
        "M12 19V5")
    }

    /**
     * 「回到最新」浮动按钮（AI 对话页）。
     *
     * lucide 的 `arrow-down`，是 [ArrowUp] 的镜像 —— 两者在同一个页面上
     * 语义正好相对（发送 = 往上送，回到底部 = 往下走），
     * 用同一套几何参数能让它们视觉重量一致。
     */
    val ArrowDown: ImageVector by lazy { lucideIcon("ArrowDown",
        "m19 12-7 7-7-7",
        "M12 5v14")
    }

    /**
     * 深度思考开关（AI 对话输入框）。
     *
     * lucide 的 `lightbulb`。与既有的 `Sparkles` 区分：
     * sparkles 用于 AI 本身（入口按钮），lightbulb 用于"开动脑筋"这个开关。
     */
    val Lightbulb: ImageVector by lazy { lucideIcon("Lightbulb",
        "M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5",
        "M9 18h6",
        "M10 22h4")
    }
}
